/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package q13transporte;

import java.awt.Image;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import q13transporte.img.Imagen;

/**
 *
 * @author jaime
 */
public class VentPrincipal extends javax.swing.JFrame {

    private ListaAutobus Buses;
    private ListaConductores Chofers;

    /**
     * Creates new form VentPrincipal
     */
    public VentPrincipal() {
        try {

            this.Chofers = new ListaConductores();
            this.Buses = new ListaAutobus();
            initComponents();
            setLocationRelativeTo(null);
            jBlimpiar.setVisible(false);
            Imagen Imagen = new Imagen();
            jPanel2.add(Imagen);
            jPanel2.repaint();
            
        } catch (SQLException | ExcepcionPersonal ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error generico", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jBlimpiar = new javax.swing.JButton();
        jBinsertar = new javax.swing.JButton();
        jBborrar = new javax.swing.JButton();
        jBbuscaMuestra = new javax.swing.JButton();
        jBlistar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAcciones = new javax.swing.JMenu();
        jMinsertar = new javax.swing.JMenu();
        jMIinsertarAutobus = new javax.swing.JMenuItem();
        jMIinsertarConductor = new javax.swing.JMenuItem();
        jMborrar = new javax.swing.JMenu();
        jMIborrarAutobus = new javax.swing.JMenuItem();
        jMIborrarConductor = new javax.swing.JMenuItem();
        jMIsalir = new javax.swing.JMenuItem();
        jMenuVer = new javax.swing.JMenu();
        jMListar = new javax.swing.JMenu();
        jMIlistarAutobus = new javax.swing.JMenuItem();
        jMIlistarConductor = new javax.swing.JMenuItem();
        jMbuscaMuestra = new javax.swing.JMenu();
        jMIbuscaMuestraAutobus = new javax.swing.JMenuItem();
        jMIbuscaMuestraConductor = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transporte Jaime");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jBlimpiar.setText("Limpiar lista");
        jBlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlimpiarActionPerformed(evt);
            }
        });

        jBinsertar.setText("Insertar");
        jBinsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBinsertarActionPerformed(evt);
            }
        });

        jBborrar.setText("Borrar");
        jBborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBborrarActionPerformed(evt);
            }
        });

        jBbuscaMuestra.setText("Busca y muestra");
        jBbuscaMuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscaMuestraActionPerformed(evt);
            }
        });

        jBlistar.setText("Listar");
        jBlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlistarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("Listar/Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBbuscaMuestra)
                            .addComponent(jBborrar)
                            .addComponent(jBinsertar)
                            .addComponent(jBlimpiar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBlistar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(46, 46, 46)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBSalir))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBlimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBinsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBborrar)
                        .addGap(15, 15, 15)
                        .addComponent(jBbuscaMuestra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBlistar)
                            .addComponent(jButton1)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jBSalir)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jMenuAcciones.setText("Acciones");

        jMinsertar.setText("Insertar");

        jMIinsertarAutobus.setText("Autobus");
        jMIinsertarAutobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIinsertarAutobusActionPerformed(evt);
            }
        });
        jMinsertar.add(jMIinsertarAutobus);

        jMIinsertarConductor.setText("Conductor");
        jMIinsertarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIinsertarConductorActionPerformed(evt);
            }
        });
        jMinsertar.add(jMIinsertarConductor);

        jMenuAcciones.add(jMinsertar);

        jMborrar.setText("Borrar");

        jMIborrarAutobus.setText("Autobus");
        jMIborrarAutobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIborrarAutobusActionPerformed(evt);
            }
        });
        jMborrar.add(jMIborrarAutobus);

        jMIborrarConductor.setText("Conductor");
        jMIborrarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIborrarConductorActionPerformed(evt);
            }
        });
        jMborrar.add(jMIborrarConductor);

        jMenuAcciones.add(jMborrar);

        jMIsalir.setText("Salir");
        jMIsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIsalirActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMIsalir);

        jMenuBar1.add(jMenuAcciones);

        jMenuVer.setText("Ver");

        jMListar.setText("Listar");

        jMIlistarAutobus.setText("Autobus");
        jMIlistarAutobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIlistarAutobusActionPerformed(evt);
            }
        });
        jMListar.add(jMIlistarAutobus);

        jMIlistarConductor.setText("Conductor");
        jMIlistarConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIlistarConductorActionPerformed(evt);
            }
        });
        jMListar.add(jMIlistarConductor);

        jMenuVer.add(jMListar);

        jMbuscaMuestra.setText("Busca y muestra");

        jMIbuscaMuestraAutobus.setText("Autobus");
        jMIbuscaMuestraAutobus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIbuscaMuestraAutobusActionPerformed(evt);
            }
        });
        jMbuscaMuestra.add(jMIbuscaMuestraAutobus);

        jMIbuscaMuestraConductor.setText("Conductor");
        jMIbuscaMuestraConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIbuscaMuestraConductorActionPerformed(evt);
            }
        });
        jMbuscaMuestra.add(jMIbuscaMuestraConductor);

        jMenuVer.add(jMbuscaMuestra);

        jMenuBar1.add(jMenuVer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jMIsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMIsalirActionPerformed

    private void jBlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlimpiarActionPerformed
        try {
            // TODO add your handling code here:
            VentEleccion ventEleccion = new VentEleccion(Buses, Chofers, "Limpiar lista");
            ventEleccion.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error generico", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBlimpiarActionPerformed

    private void jBinsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBinsertarActionPerformed
        try {
            // TODO add your handling code here:
            VentEleccion ventEleccion = new VentEleccion(Buses, Chofers, "Insertar");
            ventEleccion.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error generico", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBinsertarActionPerformed

    private void jBborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBborrarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            VentEleccion ventEleccion = new VentEleccion(Buses, Chofers, "Borrar");
            ventEleccion.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error generico", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBborrarActionPerformed

    private void jBbuscaMuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscaMuestraActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            VentEleccion ventEleccion = new VentEleccion(Buses, Chofers, "BuscaMuestra");
            ventEleccion.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error generico", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBbuscaMuestraActionPerformed

    private void jBlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlistarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            VentEleccion ventEleccion = new VentEleccion(Buses, Chofers, "Listar");
            ventEleccion.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error generico", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBlistarActionPerformed

    private void jMIinsertarAutobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIinsertarAutobusActionPerformed
        // TODO add your handling code here:
        try {
            //JOptionPane.showMessageDialog(null, "pppppppp", "Error", JOptionPane.ERROR_MESSAGE);
            VentInsBus vent = new VentInsBus(Buses, Chofers, "Insertar");
            vent.setVisible(true);
        } catch (ExcepcionPersonal ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error generico", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMIinsertarAutobusActionPerformed

    private void jMIinsertarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIinsertarConductorActionPerformed
        // TODO add your handling code here:
        VentInsCond vent;
        try {
            vent = new VentInsCond(Chofers, "Insertar");
            vent.setVisible(true);
        } catch (ExcepcionPersonal ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error generico", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMIinsertarConductorActionPerformed

    private void jMIborrarAutobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIborrarAutobusActionPerformed
        // TODO add your handling code here:
        VentBusId vent = new VentBusId(Buses, Chofers, "Borrar");
        vent.setVisible(true);
    }//GEN-LAST:event_jMIborrarAutobusActionPerformed

    private void jMIborrarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIborrarConductorActionPerformed
        // TODO add your handling code here:
        VentCondNombre vent = new VentCondNombre(Buses, Chofers, "Borrar");
        vent.setVisible(true);
    }//GEN-LAST:event_jMIborrarConductorActionPerformed

    private void jMIlistarAutobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIlistarAutobusActionPerformed
        // TODO add your handling code here:
        try {
            VentInsBus vent = new VentInsBus(Buses, Chofers, "Listar");
            vent.setVisible(true);
        } catch (ExcepcionPersonal ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error generico", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMIlistarAutobusActionPerformed

    private void jMIlistarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIlistarConductorActionPerformed
        // TODO add your handling code here:
        try {
            VentInsCond vent = new VentInsCond(Chofers, "Listar");
            vent.setVisible(true);
        } catch (ExcepcionPersonal ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error generico", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMIlistarConductorActionPerformed

    private void jMIbuscaMuestraAutobusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIbuscaMuestraAutobusActionPerformed
        // TODO add your handling code here:
        BuscaMuestra vent = new BuscaMuestra(Buses, Chofers, "BuscaMuestra");
        vent.setVisible(true);
    }//GEN-LAST:event_jMIbuscaMuestraAutobusActionPerformed

    private void jMIbuscaMuestraConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIbuscaMuestraConductorActionPerformed
        // TODO add your handling code here:
        BuscaMuestra vent = new BuscaMuestra(Chofers, "BuscaMuestra");
        vent.setVisible(true);
    }//GEN-LAST:event_jMIbuscaMuestraConductorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            VentBusTable vent = new VentBusTable(Buses, Chofers, "Listar");
            vent.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error generico", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBborrar;
    private javax.swing.JButton jBbuscaMuestra;
    private javax.swing.JButton jBinsertar;
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JButton jBlistar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuItem jMIborrarAutobus;
    private javax.swing.JMenuItem jMIborrarConductor;
    private javax.swing.JMenuItem jMIbuscaMuestraAutobus;
    private javax.swing.JMenuItem jMIbuscaMuestraConductor;
    private javax.swing.JMenuItem jMIinsertarAutobus;
    private javax.swing.JMenuItem jMIinsertarConductor;
    private javax.swing.JMenuItem jMIlistarAutobus;
    private javax.swing.JMenuItem jMIlistarConductor;
    private javax.swing.JMenuItem jMIsalir;
    private javax.swing.JMenu jMListar;
    private javax.swing.JMenu jMborrar;
    private javax.swing.JMenu jMbuscaMuestra;
    private javax.swing.JMenu jMenuAcciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuVer;
    private javax.swing.JMenu jMinsertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
